import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Red_Hat_Text } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const redHat = Red_Hat_Text({subsets:['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={redHat.className}>{children}</body>
    </html>
  )
}
